### ISSUE TITLE
Dependency Graph Submission Results in Class Cast Error

### ISSUE THREAD

**Issue by mptardy** [gradle/actions#146]
Hi

When I switch from the action `gradle/gradle-build-action@v2.4.2` to the latest version or to `gradle/actions/setup-gradle@v3` or `gradle/actions/dependency-submission@v3` I get the following error.

```
Generating dependency graph into '/home/github-runner-1/actions-runner/_work/eberhard-ebi-kafka-sink/eberhard-ebi-kafka-sink/dependency-graph-reports/dependency_submission-dependency-submission.json'
Resolving dependency graph plugin 1.3.0 from plugin repository: https://plugins.gradle.org/m2
Generating dependency graph into '/home/github-runner-1/actions-runner/_work/eberhard-ebi-kafka-sink/eberhard-ebi-kafka-sink/dependency-graph-reports/dependency_submission-dependency-submission.json'
Gradle Build did not complete successfully: Dependency Graph file will not be generated.
FAILURE: Build failed with an exception.
* What went wrong:
class org.gradle.dependencygraph.extractor.DependencyExtractorBuildService$Inject cannot be cast to class org.gradle.dependencygraph.extractor.DependencyExtractor (org.gradle.dependencygraph.extractor.DependencyExtractorBuildService$Inject is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @39bdb78c; org.gradle.dependencygraph.extractor.DependencyExtractor is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @55202cdc)
``` 

The builds are executed on self-hosted runners as we connect to a private maven repository.

~~But the setup with `gradle/gradle-build-action@v2.4.2` worked fined without any errors.~~

Does anybody have an idea what is going wrong here and how to fix it?

Your help is very much appreciated.

**Comment by bigdaz** [comment]
Thanks for the report @mptardy .
I'm a bit confused: `v2.4.2` didn't support the `dependency-graph` functionality at all: does your build fail when using `setup-gradle` without enabling the dependency graph?

The dependency graph is disabled by default for `setup-gradle`, but you can always try this to be sure: 
```
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        dependency-graph: disabled
```

If it only fails with dependency-graph enabled, then we need to sort out why. Any details you provide could be helpful:
- What version of Gradle are you running? What JDK?
- Is there any chance your build is applying the `org.gradle.github-dependency-graph-gradle-plugin` directly?
- What happens if you try to generate dependency reports locally [following these instructions](https://github.com/gradle/github-dependency-graph-gradle-plugin?tab=readme-ov-file#using-the-plugin-to-generate-dependency-reports)?

**Comment by mptardy** [comment]
Thanks @bigdaz for your help.

I only get this error when enable dependency graph, otherwise `setup-gradle` works fine.
I'm running Gradle Wrapper 8.7 with JDK 21.
I don't have `org.gradle.github-dependency-graph-gradle-plugin` applied directly.
And I can successfully generate dependency reports locally, [dependency-graph.json](https://github.com/gradle/actions/files/14941118/dependency-graph.json)

Could it be, that an old version of a jar is laying around on our self-hosted runners?

**Comment by bigdaz** [comment]
If the project generates dependency reports locally, then it's very likely this is an environmental issue with your self-hosted runner. Implementation-wise there's almost no difference between applying `SimpleDependencyGraphPlugin` and the `GitHubDependencyGraphPlugin` applied by the action.

Exactly what on your self-hosted runner is causing the issue is a mystery. Are you able to test it out on a GitHub-hosted runner? Or a "clean" self-hosted runner?

If not, you could do the following tests on your self-hosted runner:
- Run the build with a separate Gradle User Home directory, by specifying the `GRADLE_USER_HOME` env var.
- Try different JDKs
- [Try doing exactly what succeeds locally](https://github.com/gradle/github-dependency-graph-gradle-plugin?tab=readme-ov-file#using-the-plugin-to-generate-dependency-reports), without involving the `setup-gradle` or `dependency-submission` action: 
   - Write the init-script to apply the `SimpleDependencyGraphPlugin`
   - Use a `run` action to execute the `gradlew` command

**Comment by mptardy** [comment]
I've found the issue. We've set up these self-hosted runners with a special `settings.xml`, where our internal artifact repository is configured in. Therefore, we use `overwrite-settings: 'false'` when using `actions/setup-java@v4`.
As soon as I tried without `overwrite-settings: 'false'` everything worked fine. But the `settings.xml` got overwritten with the following content.
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>github</id>
      <username>${env.GITHUB_ACTOR}</username>
      <password>${env.GITHUB_TOKEN}</password>
    </server>
  </servers>
</settings>
``` 
I've just copied the `server` tag to our custom `settings.xml` and now everything works fine.
In the end, this all makes sense, but the error was very missleading.

Thanks again @bigdaz for your help.

**Comment by bigdaz** [comment]
Thanks for letting us know. I can't think of how losing the custom artifactory setting would cause the error you saw, so I'm not sure what we can do to improve the experience for other users with similar problems.

But I'll keep an eye out for any similar reports

**Comment by bigdaz** [comment]
@mptardy Can you confirm that you've got this working again with `overwrite-settings: false`

**Comment by mptardy** [comment]
@bigdaz yes, I can confirm that it works with `overwrite-settings: false`. I'm using the following workflow.

```yaml
name: Dependency Submission

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'build.gradle.kts', 'gradle.properties', 'repositories.gradle.kts', 'settings.gradle.kts', 'gradle/libs.versions.toml', 'buildSrc/build.gradle.kts', 'buildSrc/settings.gradle.kts', '.github/workflows/dependency-submission.yml' ]

jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on:
      group: mp-default
      labels: [ self-hosted, Linux, X64 ]
    concurrency:
      group: '${{ github.workflow }}: ${{ github.ref }}'
      cancel-in-progress: true
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21.0.2+14'
          overwrite-settings: 'false'
      - name: Generate and submit dependency graph
        id: generate-and-submit-dependency-graph
        uses: gradle/actions/dependency-submission@v3
```

But I don't understand how the exception I had is related to the missing `<server>` block.
I've seen that the `settings.xml` got overwritten because I tried it once without `overwrite-settings: false`. The new `settings.xml` only contained the `<server>` block.
That's when I had the idea to restore our custom `settings.xml` and adding the `<server>` block and it worked.
