### ISSUE TITLE
[Android] setup-gradle: After canceling build - Could not read workspace metadata from `C:\Users\runneradmin\.gradle\caches\transforms-4\0e69aaacf4af78f6c6c3f80936fa8b36\metadata.bin`

### ISSUE THREAD

**Issue by david-allison** [gradle/actions#167]
### Description

`main` branch: After cancelling a workflow, we encountered the following error on our next CI run

```
Execution failed for task ':AnkiDroid:checkPlayDebugAarMetadata'.
> A build operation failed.
      Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\0e69aaacf4af78f6c6c3f80936fa8b36\metadata.bin
   > Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\0e69aaacf4af78f6c6c3f80936fa8b36\metadata.bin
```

I suspect that this is an instance of https://github.com/gradle/actions/issues/71. I have done no further diagnostics and this may be related to another part of our CI

* https://github.com/gradle/actions/issues/71

<hr>

### Workaround

We used `cache-disabled: true` as a temporary workaround

* https://github.com/ankidroid/Anki-Android/commit/f9b7ee6818b680e9a97fd57c01e25626520578e0

<hr>

### Additional information
`gradle/actions/setup-gradle@v3` on GitHub Actions (`windows-latest`).

* `gradle/actions@v3.2.1 (SHA:1168cd3d07c1876a65e1724114de42ccbdfa7b78)`
* `gradle-wrapper: 8.7`
* `gradle-home-cache-cleanup: true`

<details>

<summary>setup-gradle@v3 YML</summary>

```yaml
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        timeout-minutes: 5
        with:
          # Only write to the cache for builds on the 'main' branches, stops branches evicting main cache
          # Builds on other branches will only read from main branch cache writes
          # Comment this and the with: above out for performance testing on a branch
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-home-cache-cleanup: true
```

</details>

The workflow on `main` was cancelled due to another pull request being merged

<details>

<summary>@bogdanzurac has also reported this is occurring on private repos on their company's CI [Linux]</summary>

> @david-allison We've been experiencing this issue on some of our internal projects as well. While searching for this issue online, this is the only other reference I could find.
> 
> From what I can see, you're using Windows CI + updated recently to Gradle 8.7. Our CI runs Linux and Gradle 8.6/8.7 and we're also encountering the same problem. When have you first started seeing this? Does it only happen on CI or locally as well? Does it only happen when running unit tests?

https://github.com/ankidroid/Anki-Android/issues/16161#issuecomment-2051171431

</details>

<hr>

### Links

* https://github.com/ankidroid/Anki-Android/commits/main/.github/workflows/tests_unit.yml
  * Workflow history (`main`):  https://github.com/ankidroid/Anki-Android/actions?query=branch%3Amain
    * [Last success](https://github.com/ankidroid/Anki-Android/actions/runs/8644871195)
    * [Cancelled workflow](https://github.com/ankidroid/Anki-Android/actions/runs/8645703463)
    * [First failure](https://github.com/ankidroid/Anki-Android/actions/runs/8645719390)
* Issue
  * https://github.com/ankidroid/Anki-Android/issues/16161
* We previously had an issue with the transform cache
  * https://github.com/gradle/actions/issues/47
