### ISSUE TITLE
Provide input parameters for key environment variable supported by GitHub Dependency Graph plugin

### ISSUE THREAD

**Issue by bigdaz** [gradle/actions#193]
Currently, there are some key configuration inputs to the GitHub Dependency Graph plugin that can only be provided via environment variables. 
The full list is [here](https://github.com/gradle/github-dependency-graph-gradle-plugin?tab=readme-ov-file#required-environment-variables), [here](https://github.com/gradle/github-dependency-graph-gradle-plugin?tab=readme-ov-file#filtering-which-gradle-configurations-contribute-to-the-dependency-graph) and [here](https://github.com/gradle/github-dependency-graph-gradle-plugin?tab=readme-ov-file#controlling-the-scope-of-dependencies-in-the-dependency-graph).

We don't need to support all of these variables, since some are set by the action and there's little or no reason to override them. We also only need to support these for `dependency-submission`. When `setup-gradle` with `dependency-graph` enabled, users can continue to provide environment variables.

For now, we should at least provide:
- `report-dir`: `DEPENDENCY_GRAPH_REPORT_DIR` with paths resolved relative to the project workspace
- `exclude-projects`: `DEPENDENCY_GRAPH_EXCLUDE_PROJECTS`
- `exclude-configurations`: `DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS`
- Possibly the 'include' variations as well.

For now we can leave out the variables that control the 'runtime' scope, since these are largely experimental. Ideally, the plugin would make a good guess at the dependencies that are in runtime scope, but it's not trivial.

**Comment by radoslaw-panuszewski** [comment]
> When setup-gradle with dependency-graph enabled, users can continue to provide environment variables.

For the `setup-gradle` users, the configuration via environment variables is very inconvenient right now.

We first tried the naive approach:
```yaml
steps:
  - uses: gradle/actions/setup-gradle@v3
    env:
      DEPENDENCY_GRAPH_REPORT_DIR: ${{ runner.temp }}/setup-gradle 

  - run: ./gradlew build
```

But it failed with a strange Groovy error:
```
Initialization script '/home/github/.gradle/init.d/gradle-actions.github-dependency-graph.init.gradle' line: 43

* What went wrong:
A problem occurred evaluating initialization script.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
  	[class java.lang.String, class java.lang.String]
  	[class java.io.File, class java.lang.String]
```

After a little of debugging, it turned out that the `DEPENDENCY_GRAPH_REPORT_DIR` is not exported globally and the step executing `./gradlew` doesn't see it. The issue is that `maybeExportVariable` doesn't export variable if it's already present:

```groovy
function maybeExportVariable(variableName: string, value: unknown): void {
    if (!process.env[variableName]) {
        core.exportVariable(variableName, value)
    }
}
```

To make it working, we need to globally export the variable. Currently, we do it this way:
```yaml
steps:
  - run: echo "DEPENDENCY_GRAPH_REPORT_DIR=${{ runner.temp }}/setup-gradle" >> $GITHUB_ENV
    shell: bash

  - uses: gradle/actions/setup-gradle@v3

  - run: ./gradlew build
```

As I said, it's inconvenient for us. We would love to have the `report-dir` input parameter for `setup-gradle` and I will happily provide a PR if I get a green light for that ;) @bigdaz
