### ISSUE TITLE
Included builds containing build logic prevent configuration-cache reuse

### ISSUE THREAD

**Issue by scana** [gradle/actions#21]
Hi!

Just tried out Gradle 8.6 with `gradle/actions/setup-gradle@v3` and it seems like a `build-conventions` (https://docs.gradle.org/current/samples/sample_sharing_convention_plugins_with_build_logic.html) related task input change is preventing my configuration-cache from being reused.
They do seem to cache fine on local builds.

```
Calculating task graph as configuration cache cannot be reused because 
an input to task ':build-conventions:generatePluginAdapters' has changed.
```

Sample job that I run:
```yaml
- name: Run ktlint
  uses: gradle/actions/setup-gradle@v3
  with:
    gradle-home-cache-cleanup: true
    cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
    arguments: ktlintCheck
```

Is there any chance this might be related to `gradle-home-cache-cleanup` https://github.com/gradle/actions/issues/19 ?
If not, is there anything else that we should cache?

I suppose build conventions falls under this category:
> caches/\<version\>/kotlin-dsl and caches/\<version\>/scripts: These are the compiled build scripts. The Kotlin ones in particular can benefit from caching.
