### ISSUE TITLE
Failing to restore Gradle Cache because of "Error: Content-Length not found on blob response"

### ISSUE THREAD

**Issue by buehlerjochen** [gradle/actions#235]
Hi,

I would like to use the `setup-gradle` action to store and restore the Gradle caches. But the action fails every time due to errors like this:
` Warning: Failed to restore gradle-home-v1|Linux|compatibility-test[b2e82155fc439b8351abee85b9386021]-8410f0ac768ab745eaf88d7100791f8a4378a0bd: Error: Content-Length not found on blob response`

We have a build with multiple jobs, the relevant ones are:
* compile job - compile code and run unit tests, should store cache
* compatibility tests - (actually a matrix job) runs compatibility tests on the project and should reuse the cache and compiled output of compile job (read-only cache)

These are the jobs (simplified) from the workflow file:
```
jobs:
  build-commit:
    steps:

    # preparation, configuration

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    # Use setup-gradle step to save/restore Gradle cache and speed up builds
    - name: Setup Gradle cache
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
    - name: "Validate Gradle Wrapper"
      uses: gradle/wrapper-validation-action@v1

    # build & publish

    - name: Gradle build
      run: ./gradlew -i --stacktrace clean build

  compatibility-test:
    strategy:
      matrix:
        gradle-version: [ '7.3', '8.6' ]

    needs: build-commit

    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      # Use setup-gradle step to save/restore Gradle cache and speed up builds
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: true
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1

      - name: Compatibility test
        run: ./gradlew -i --stacktrace compatibilitytest
        env:
          GRADLE_VERSION: ${{ matrix.gradle-version }}
```

I can see how the action stores the cache for the compile job, but then fails when restoring during:
* follow up compatibility test jobs
* subsequent compile jobs on new build runs

`generate-job-summary` is enabled and I can see how the action stores cache entries in the compile job, but does not restore them in the compatibility test job and in subsequent build executions. For the failed restore attempts, it prints these details:
```
    Entry: Gradle User Home
    Requested Key : gradle-home-v1|Linux|compatibility-test[b2e82155fc439b8351abee85b9386021]-8410f0ac768ab745eaf88d7100791f8a4378a0bd
    Restored  Key : 
              Size: 
              (Entry not restored: Content-Length not found on blob response)
    Saved     Key : 
              Size: 
              (Entry not saved: cache is read-only)
```

We are using:
* latest v3 version of the action
* GHES 3.11.9

Could it be that there is a compatibility issue with GHES? Or am I doing something wrong?
