### ISSUE TITLE
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read

### ISSUE THREAD

**Issue by zoey-juan** [gradle/actions#238]
Hi,
We have checked several discussion and reported issues but still we're getting a bunch of warnings after updating to  `gradle/actions/setup-gradle@v3`. I'm wondering if any suggestions how to fix those issues properly.

## Setup
Added the gradle workaround.
```
    - name: Set /usr/bin/gradle alias to gradlew # workaround: https://github.com/gradle/actions/issues/33
      shell: bash
      run: sudo ln -s "$GITHUB_WORKSPACE/gradlew" /usr/bin/gradle
    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        # Excludes ~/.gradle/caches/build-cache-1/ already provided by GE remote caching
        gradle-home-cache-excludes: caches/build-cache-gu
        gradle-home-cache-cleanup: true
        cache-read-only: false // for testing on non-master branch only

```
Disable local cache regarding to the [readme doc](https://github.com/gradle/actions/blob/af6e5767241073b8ab20cc8cf7e95ec63fadc160/docs/setup-gradle.md?plain=1#L373)
```
buildCache {
    local {
        isEnabled = System.getenv("CI") == null
        directory = File(gradle.gradleUserHomeDir, "build-cache-gu")
        removeUnusedEntriesAfterDays = 15
    }
    remote<HttpBuildCache> {
        isEnabled = System.getenv("CI") != null
        isPush = System.getenv("CI") != null
        setUrl("$gradleEnterpriseUrl/cache/")
    }
}
```

## Warnings
<img width="1099" alt="Screenshot 2024-05-31 at 20 16 03" src="https://github.com/gradle/gradle-build-action/assets/18564149/231be667-5efb-4af0-8b37-5ed28cb53ff6">

1. 
```
build_debug / android-build
Unhandled error in Gradle post-action - job will continue: Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
```
2.
```
build_debug / android-build
Failed to save cache entry with path '/home/runner/.gradle/caches/transforms-4/*/ /home/runner/.gradle/caches/*/transforms/*/' and key: gradle-transforms-v1-feb3ccfac262ee449fb58b558de5457a: Error: Cache service responded with 429 during upload chunk.
```
