### ISSUE TITLE
gradle/actions/dependency-submission needs to work on tag builds

### ISSUE THREAD

**Issue by xenoterracide** [gradle/actions#242]
### Current Behavior

A release is likely to be built of a tag which points to a commit on main

> Submitted dependency-graph-reports/release-release.json: The snapshot was accepted, but it is not for the default branch. It will not update dependency results for the repository.

minimal details of workflow, 

### Expected Behavior

submission to a ref that points to a commit in the default branch should work.

### Steps to Reproduce

obviously you'll have to add some actual gradle build steps, but it's not significant in this issue I think.

```yml
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write  
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - ...
      - uses: gradle/actions/dependency-submission@v3
```

### Gradle version

8.7

### Your Environment (optional)

checkout peformed differently than normal due to https://github.com/actions/checkout/issues/882

I'm not certain whether or not the dependency report should really be used on every build of the default branch vs an actual release. I guess for now it'll have to be every build of the default branch
