### ISSUE TITLE
gradle/actions/setup-gradle: 'wrapper' gradle-version does not use Gradle wrapper version

### ISSUE THREAD

**Issue by Virtlink** [gradle/actions#273]
I use the `gradle/actions/setup-gradle` task with a version matrix `gradle-version: ['wrapper', '7.6.4', '8.8']`. For the `'wrapper'` value, I expected it to use the `gradlew` wrapper version of Gradle (8.6 in my case). Instead, it uses a seemingly random (latest?) version of Gradle (Gradle 8.8 in my case).

For the explicitly specified versions 7.6.4 and 8.8, it works correctly, downloading and setting up that Gradle version. The subsequent call to`gradle build` executes with the intended Gradle version. However, for the `'wrapper'` version of Gradle, which is [Gradle 8.6](https://github.com/Virtlink/kotlin-jvm-template/blob/main/gradle/wrapper/gradle-wrapper.properties#L3) in my project, it instead [uses Gradle 8.8](https://github.com/Virtlink/kotlin-jvm-template/actions/runs/9741721408/job/26881500409#step:6:21).

This is the relevant part of [my workflow](https://github.com/Virtlink/kotlin-jvm-template/blob/main/.github/workflows/build.yaml):

```yaml
jobs:
  build:
    strategy:
      matrix:
        gradle-version: ['wrapper', '7.6.4', '8.8']
    steps:
      # ...
      - name: "Setup Gradle ${{ matrix.gradle-version }}"
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ matrix.gradle-version }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: 'Build'
        run: |
          gradle build
```

**Comment by bigdaz** [comment]
Thanks for reporting. You're correct that the `wrapper` version keyword doesn't work using `setup-gradle` with a separate build step. This feature is a leftover from the `gradle-build-action` which provided a `arguments` parameter to directly execute Gradle.

Using `gradle-version: wrapper` with `setup-gradle` doesn't make sense, since it doesn't download any Gradle version and it doesn't (cannot) update the path so that `gradle == ./gradlew`.

In order to use a matrix to execute with multiple Gradle versions (including the wrapper), you'll need to do something like:

```yaml
jobs:
  build:
    strategy:
      matrix:
        gradle-version: ['wrapper', '7.6.4', '8.8']
        gradle-command: ['gradle']
        include:
        - gradle-version: 'wrapper'
          gradle-command: './gradlew'

    steps:
      # ...
      - name: "Setup Gradle ${{ matrix.gradle-version }}"
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ matrix.gradle-version }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: 'Build'
        run: |
          ${{matrix.gradle-command}} build
```

This isn't ideal, but it should provide a workaround. 
I'll leave this issue open pending a better solution (if possible).
