### ISSUE TITLE
Trouble caching build outputs

### ISSUE THREAD

**Issue by mumrah** [gradle/actions#288]
I am working on what I presume is a pretty typical setup for Github actions and Gradle. I would like to have a job that runs on every commit on my main branch (`trunk`) that populates a cache of dependencies, gradle binary, as well as build outputs (compiled java/scala classes). Then on pull requests, I'm hoping to leverage incremental builds based off this cache to reduce build times.

I have the following workflow configuration

```yml
name: build

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      env:
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
      with:
        gradle-version: current
        gradle-home-cache-includes: |
          caches
          notifications
          jdks
        gradle-home-cache-cleanup: true
        cache-overwrite-existing: true
    - name: Gradle build
      run: ./gradlew --build-cache --info :metadata:compileTestJava
```

But when run on my default branch, I do not see any entries  for`caches/build-cache-1` in the "Post" job.

In the Gradle output, I see 

```
Using the build cache is enabled, but no build caches are configured or enabled.
```

as well as many tasks reporting "Build cache is disabled" despite passing the `--build-cache` argument to gradlew.

```
> Task :clients:processTestResources
Caching disabled for task ':clients:processTestResources' because:
  Build cache is disabled
  Not worth caching
Task ':clients:processTestResources' is not up-to-date because:
  No history is available.
```

Here is an example run https://github.com/mumrah/kafka/actions/runs/9920478886/job/27407411362
