### ISSUE TITLE
🐞 Actions doesn't see gradle with version 8.10

### ISSUE THREAD

**Issue by ylazakovich** [gradle/actions#340]
```yaml
     - name: Set up JDK
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: "corretto"
          cache: "gradle"
          java-version: "17"
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4
        with:
          gradle-version: 8.10
```

As result uses gradle of version 8.1 instead of 8.10
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/b43c7e59-7d6f-4bf5-a410-fbd840b650a4">
