### ISSUE TITLE
Improve caching behaviour when using GitHub Merge Queue

### ISSUE THREAD

**Issue by hanneskaeufler** [gradle/actions#363]
Due to the high number of daily PRs to a repo, we have enabled [githubs merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues) feature:

> The merge queue provides the same benefits as the Require branches to be up to date before merging branch protection, but does not require a pull request author to update their pull request branch and wait for status checks to finish before trying to merge.

Due to the fact that

> The merge queue will ensure the pull request's changes pass all required status checks when applied to the latest version of the target branch and any pull requests already in the queue.

our workflow definitions mostly look like

```yaml
name: Test
on:
  workflow_dispatch:
  pull_request:
  merge_group:
```

Notice _specifically the absence of_

```yaml
on:
  push:
    branches:
      - main
```

because the merge queue pretty much prevents any merges from breaking `main` already, so running test jobs on push to `main` is wasted money. However, **this prevents PR builds from profiting from the gradle cache**.

**Is there something that can be done in `setup-gradle`, which would allow PR builds to read the cache created in the merge queue builds by default?**

This is how all the steps look:

```
- name: Setup Gradle
  uses: gradle/actions/setup-gradle@v4.0.1
  with:
    cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
```
