### ISSUE TITLE
Does the dependency-submission action support a monorepo configuration?

### ISSUE THREAD

**Issue by Toru-Takagi** [gradle/actions#379]
My repository is structured as a monorepo and is organized as follows:

```
directory-name
  ┣ microservice-a
  ┃      ┣ build.gradle.kts
  ┃      ┣ gradle.properties
  ┃      ┣ gradlew
  ┃      ┗ settings.gradle.kts
  ┣ microservice-b
  ┃      ┣ build.gradle.kts
  ┃      ┣ gradle.properties
  ┃      ┣ gradlew
  ┃      ┗ settings.gradle.kts
  ┣ microservice-c
  ┃      ┗ go.mod
  ┣ microservice-d
  ┃      ┗ package.json
  ┗ microservice-e
           ┣ build.gradle.kts
           ┣ gradle.properties
           ┣ gradlew
           ┗ settings.gradle.kts
```

Here is the GitHub Actions configuration file.

```yml
name: Dependency Submission

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Generate and submit dependency graph for microservice-a
        env:
          GITHUB_JOB_CORRELATOR: "${{ github.workflow }}-${{ github.job }}-microservice-a"
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: "microservice-a"
      - name: Generate and submit dependency graph for microservice-b
        env:
          GITHUB_JOB_CORRELATOR: "${{ github.workflow }}-${{ github.job }}-microservice-b"
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: "microservice-b"
      - name: Generate and submit dependency graph for microservice-c
        env:
          GITHUB_JOB_CORRELATOR: "${{ github.workflow }}-${{ github.job }}-microservice-c"
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: "microservice-c"
```
