### ISSUE TITLE
gradle-wrapper.jar verification fails when stored via git-lfs

### ISSUE THREAD

**Issue by LivingWithHippos** [gradle/actions#456]
If the jars are stored with git-lfs the checksum will fail, the lfs flag needs to be added

```yaml
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # gradle-wrapper.jar verification will fail without this
```

otherwise there will be a mismatch, for example gradle 8.10

```sh
❯ sha256sum gradle-wrapper.jar
2db75c40782f5e8ba1fc278a5574bab070adccb2d21ca5a6e5ed840888448046  gradle-wrapper.jar
```

action error:

 ```sh
✗ Found unknown Gradle Wrapper JAR files:
  f629a612b54373f56f950e11394850bb65f87dd68d7731fcde2b99564dcfbf78 app/gradle/wrapper/gradle-wrapper.jar
Error: Error: At least one Gradle Wrapper Jar failed validation!
```

Not really a bug, posting this for reference. Maybe a check could be added to display a more useful error message?
