### ISSUE TITLE
setup-gradle is not able to use the configuration cache

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/actions#457]
I am trying to get configuration cache to work with setup-gradle github action.. but it doesn't seem to be working.

Here is the reason that shows up every time:
Calculating task graph as configuration cache cannot be reused because file '../../../../../../src900954567/src/actions-runner/_work/messaging/messaging/settings.gradle.kts' has been removed.

We are using aws hosted github runners.

The relevant github action setup is as follows:
```
    - name: Setup Java
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        gradle-version: "wrapper"
        cache-read-only: false
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        cache-overwrite-existing: true
        add-job-summary-as-pr-comment: on-failure
        cache-cleanup: never
```
