### ISSUE TITLE
Clarification on caching documetation

### ISSUE THREAD

**Issue by mumrah** [gradle/actions#555]
In the [docs](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#select-which-jobs-should-write-to-the-cache) it is suggested to use a DAG like

```
compile-and-unit-test 
 | - integration-test (A)
 | - integration-test (B)
 \ - integration-test (C)
```

```yaml
jobs:
  compile-and-unit-test:
    steps:
      - uses: gradle/actions/setup-gradle
      - run: ./gradlew test
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        var: [A, B, C]
    needs: compile-and-unit-test
    steps:
      - uses: gradle/actions/setup-gradle
      - run: ./gradlew integrationTest
```

where "compile-and-unit-test" writes to the cache, and the matrix "integration-test" jobs will read from the cache. 

Does this actually work? Since the cache keys include the job ID, how does the "integration-test" match the correct keys? It seems that "compile-and-unit-test" will create keys like

```
gradle-home-v1|Linux-X64|compile-and-unit-test[b8a35c2f917259958c9abe8f2ff1b5ff]-d08e6a8e58ddb969c3122298070be285a86bb258 
```

According to the matching strategy for cache keys, the Job ID must match in all but the last case.

```
    1) An exact match on OS, job id, workflow name, matrix, and Git SHA
    2) The most recent entry saved for the same OS, job id, workflow name, and matrix values
    3) The most recent entry saved for the same OS and job id
    4) The most recent entry saved for the same OS
```

Does this example workflow really rely on the fall through case where it is just matching on the same OS? Wouldn't this mean the integration-test jobs would restore the latest key matching

```
gradle-home-v1|Linux-X64|*[*]-* 
```

**Comment by bigdaz** [comment]
> Does this example workflow really rely on the fall through case where it is just matching on the same OS? Wouldn't this mean the integration-test jobs would restore the latest key matching `gradle-home-v1|Linux-X64|*[*]-*`

Yes this is how the cache entry matching currently works. 
- On the first run of `integration-test (A)` we would use the most recent cache entry starting with `gradle-home-v1|Linux-X64|`, since a more specific match would not be available.
- On each subsequent run, we should find a matching entry like `gradle-home-v1|Linux-X64|integration-test[--hash-representing-A--]`, and use this.

So after the initial run, we'll be using cache entries written by a previous execution of the same `integration-test (A)` job, which is likely to be optimal.

A potential optimization for the "first run" scenario would be to use the [needs context](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#needs-context) to look for cache entries written by dependent jobs. If we implemented this, we'd first search for `gradle-home-v1|Linux-X64|compile-and-unit-test` before looking for entries matching `gradle-home-v1|Linux-X64|`.

(Note that your example doesn't actually express the dependency of `integration-test` on `compile-and-unit-test`. I assume you intended
```
jobs:
  compile-and-unit-test:
    ...
  integration-test:
    needs: compile-and-unit-test
    strategy:
       ...
```

**Comment by mumrah** [comment]
@bigdaz thanks for the details. I've edited my original message to include the `needs` as you mentioned. I also numbered the cache matching cases for clarity in the discussion.

> On the first run of integration-test (A) we would use the most recent cache entry starting with gradle-home-v1|Linux-X64|, since a more specific match would not be available.

Ok, so we would be matching with case 4 in the `integration-test` job. Doesn't this mean we could potentially load the wrong cache from different build? Let's say there's some other concurrently running mainline build. Is there a race condition between this unrelated job and the `compile-and-unit-test` completing which would result in the wrong cache being loaded by `integration-test`?

In other words, for this particular use case, are we relying on the fact that the cache produced by `compile-and-unit-test` happens to be the most recent?

---

Accounting for the `needs` makes sense in terms of cache resolution. Maybe allowing the workflow to pass in a part of the cache key could work for this? For example,

```
jobs:
  compile-and-unit-test:
    steps:
      - uses: gradle/actions/setup-gradle
      - run: ./gradlew test
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        var: [A, B, C]
    needs: compile-and-unit-test
    steps:
      - uses: gradle/actions/setup-gradle
      - with:
          cache-context: 'compile-and-unit-test'   <-- new setup-gradle config
      - run: ./gradlew integrationTest
```

Could create a dependency resolution like:

1) gradle-home-v1|Linux-X64|compile-and-unit-test[matrix hash][Git SHA]
2) gradle-home-v1|Linux-X64|compile-and-unit-test[matrix hash]
3) gradle-home-v1|Linux-X64|compile-and-unit-test
4) gradle-home-v1|Linux-X64


By overriding the job ID you could also solve another quirk of setup-gradle which is that you have to have matching job IDs between your mainline builds and PRs builds.
