### ISSUE TITLE
Provide an action to install the `gradle-profiler`

### ISSUE THREAD

**Issue by trevjonez** [gradle/actions#591]
Doing a simple composite action by hand to install a distro of the tool from maven central isn't too bad but it would be nice if we had a central off the shelf action we could depend on to do it correctly.

```yml
name: 'Install gradle-profiler'
description: 'Install gradle-profiler'
inputs:
  version:
    description: "Tag version to install"
    required: true
    default: "0.22.0"
runs:
  using: "composite"
  steps:
    - name: Install gradle-profiler ${{ inputs.version }}
      shell: bash
      run: |
        cd ../
        wget https://repo1.maven.org/maven2/org/gradle/profiler/gradle-profiler/${{ inputs.version }}/gradle-profiler-${{ inputs.version }}.zip
        unzip gradle-profiler-${{ inputs.version }}.zip
        ./gradle-profiler-${{ inputs.version }}/bin/gradle-profiler -v
        echo "$(pwd)/gradle-profiler-${{ inputs.version }}/bin" >> "$GITHUB_PATH"
```
