### ISSUE TITLE
Include `.gradle-test-kit` in caches as well

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/actions#614]
I'm not seeing any logic in place for caching the directory generated by testkit. It might be nice if that were done automatically as well.

We currently have this logic in `ktlint-gradle` to do this:

```yml
      - name: Restore TestKit cache
        # Inspired by https://github.com/actions/cache/issues/432#issuecomment-740376179
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            plugin/.gradle-test-kit/caches/modules-2
            plugin/.gradle-test-kit/caches/files-2.1
            plugin/.gradle-test-kit/caches/metadata-2.96
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}-
            ${{ runner.os }}-gradle-wrapper-
```
