### ISSUE TITLE
`gradle/actions/setup-gradle` configuration cache without build cache

### ISSUE THREAD

**Issue by MarcusDunn** [gradle/actions#649]
I have a remote build cache which lives on the same machine as my CI runners. As per this actions recommendation, I've set `cache-disabled: 'true'` so the runner will use the remote cache. Unfortunately, there seems to be no first-class support for remote configuration caching beyond this action.

As a result, by disabling the action-provided cache in favor of the hosted remote cache, I've lost out on configuration caching . We have ~90% cache hits on most runs,  so configuration takes up a significant amount of time (~20-30%)

I would like the ability to leverage the configuration caching provided by this action, but *not* the build cache.

For reference here is by configuration

```yaml
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@787f6c043d4a67a754aba88c7841669a3130ea65
        with:
          validate-wrappers: true
          cache-disabled: 'true'
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
```
