### ISSUE TITLE
dependency submission Integrating the dependency-review-action example doesn't seem to require a second job

### ISSUE THREAD

**Issue by tspascoal** [gradle/actions#68]
For dependency submission  action, why does the example in [Integrating the dependency-review-action](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#integrating-the-dependency-review-action) section requires a second job?

Looking at the [implementation](https://github.com/gradle/actions/blob/60b8089f55223103fc34537afd709d793b43e290/dependency-submission/action.yml#L79) the submission is done immediately after the generation with the `download-and-submit` parameter and the complete step in `setup-gradle` action skips any action when the input is `download-and-submit`  ([src](https://github.com/gradle/actions/blob/60b8089f55223103fc34537afd709d793b43e290/sources/src/dependency-graph.ts#L64))

So this makes me conclude that example could be much simpler and not require a second job.

```
name: Dependency review for pull requests

on: [ pull_request ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
    - name: Perform dependency review
      uses: actions/dependency-review-action@v3
```

Did I miss something in my analysis?
